import Head from 'next/head'
import Image from 'next/image'
import { Fragment } from 'react'
import Layout from '../components/base/Layout'
import Hero from '../components/home/hero'
import ProductList from '../components/products/product-list'

export default function Home() {
  return (
    <Layout>
      <Fragment>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <main>
          <Hero/>
          <div className="album py-5 bg-light">
            <div className="container">
              <ProductList items={[1,2,3,4,5,6]}/>
            </div>
          </div>
        </main>
      </Fragment>
    </Layout>
  )
}
