import Head from 'next/head'
import Image from 'next/image'
import { Fragment } from 'react'
import Layout from '../components/base/Layout'
import Hero from '../components/home/hero'
import ProductList from '../components/products/product-list'
import Link from 'next/link';

export default function Home() {
  return (
    <Layout>
      <Fragment>
        <Head>
          <title>My Commerce</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <main>
          <Hero/>
          <div className="album py-5 bg-light">
            <div className="container">
              <h3>Viu recentemente</h3>
              <ProductList items={[1,2,3,4]}/>
              <br/>
              <h3>Produtos em destaque</h3>
              <ProductList items={[1,2,3,4]}/>
              <br/>
              <br/>
              <div className="text-center">
                <Link href="/shop"><a className="btn btn-outline-secondary">Mais produtos...</a></Link>
              </div>
            </div>
          </div>
        </main>
      </Fragment>
    </Layout>
  )
}
