import Head from 'next/head'
import Image from 'next/image'
import { Fragment } from 'react'
import Layout from '../components/base/Layout'
import Hero from '../components/home/hero'
import ProductList from '../components/products/product-list'
import Link from 'next/link';

export default function Home(props) {
  return (
    <Layout>
        <Head>
          <title>MyShop</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <main>
          <Hero goShopBtn={true} contactBtn={true}>
            <h1 className="fw-light">Bem vindo a MyShop</h1>
            <p className="lead text-muted">Aqui você encontra os melhores produtos nos melhores preços!</p>
          </Hero>
          <div className="album py-5 bg-light">
            <div className="container">
              <h3>Produtos em destaque</h3>
              <ProductList items={props.items}/>
              <br/>
              { props.recent && props.recent.length > 0 && <h3>Visitados recentemente</h3>}
              { props.recent && props.recent.length > 0 && <ProductList items={props.recent}/> }
              <br/>
              <br/>
              <div className="text-center">
                <Link href="/shop"><a className="btn btn-outline-secondary">Mais produtos...</a></Link>
              </div>
            </div>
          </div>
        </main>
    </Layout>
  );

  
}

export async function getStaticProps(context){
  let itens = [];
  const req = await fetch('http://localhost:3000/api/featured?limit=4').catch(err =>{});
  if (req)
  {
    itens = await req.json();
  }
  else{
    itens  = [
      {
        nome: "Ergonomic Fresh Bacon",
        descricao: "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
        categoria: "Generic",
        imagem: "http://placeimg.com/640/480/animals",
        preco: "174.00",
        material: "Concrete",
        departamento: "Garden",
        id: "1-28"
      },
      {
        nome: "Awesome Frozen Soap",
        descricao: "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
        categoria: "Small",
        imagem: "http://placeimg.com/640/480/transport",
        preco: "404.00",
        material: "Rubber",
        departamento: "",
        id: "2-36"
      },
      {
        nome: "Fantastic Steel Salad",
        descricao: "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
        categoria: "Refined",
        imagem: "http://placeimg.com/640/480/nature",
        preco: "716.00",
        material: "Metal",
        departamento: "Tools",
        id: "1-2"
      },
      {
        nome: "Generic Plastic Bike",
        descricao: "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
        categoria: "Generic",
        imagem: "http://placeimg.com/640/480/abstract",
        preco: "14.00",
        material: "Granite",
        departamento: "",
        id: "2-6"
      }
    ];
  }

  return {
    props: {
      items: itens,
      recent: []
    },
    revalidate: 60
  }
}
